GET http://localhost:8000/api/v1/users
Accept: application/json

###

POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

###

POST http://localhost:8000/
Content-Type: application/json

{
  "username": "user",
  "full_name": "full name",
  "yoba": "LOL"
}

###

POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

###