GET http://localhost:8000/api/v1/users
Accept: application/json

###

POST http://localhost:8000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NTc3NDk2ODQsInN1YiI6ImFjY2VzcyJ9._CrXlzLMDodE96LvEFOzr0wyJqC9ZikIE5BTe23wkHc

{
  "username": "user1",
  "password": "123456"
}

###

POST http://localhost:8000/
Content-Type: application/json

{
  "username": "user",
  "full_name": "full name",
  "yoba": "LOL"
}

###

POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

###

GET http://localhost:8000/api/v1/current_user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NTc3NjcxOTQsInN1YiI6ImFjY2VzcyJ9.mXN37iD7kmKiXKPN4LZq4eL0KuXB0ew2u4k7AX1o89U

###

GET http://localhost:8000/api/v1/projects
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NTgwODkwMDgsInN1YiI6ImFjY2VzcyJ9.F8CUqOdQWg3fGIWT-758uHEtDdbsbdx_1b_nq-WxzWM

###

GET http://localhost:8000/api/v1/projects/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NTc4NTcxMzgsInN1YiI6ImFjY2VzcyJ9.RzAH3Sz3mzdsfBwELz7pyuamgAXBXoAqpK5cH5XGtu8

###