version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: scrum_ng
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: "db:5432"
    depends_on:
      - db