"""add table for finished tasks

Revision ID: 3b7decdce303
Revises: 6c48ea066952
Create Date: 2019-05-11 19:58:29.751419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7decdce303'
down_revision = '6c48ea066952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_tasks',
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('sprint_id')
    )
    op.create_index(op.f('ix_finished_tasks_task_id'), 'finished_tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finished_tasks_task_id'), table_name='finished_tasks')
    op.drop_table('finished_tasks')
    # ### end Alembic commands ###
