"""add sprint length field to projects

Revision ID: 6c48ea066952
Revises: d7edea05b2fe
Create Date: 2019-05-11 11:36:11.021652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c48ea066952'
down_revision = 'd7edea05b2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sprint_length', sa.Integer(),
                                        nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sprint_length')
    # ### end Alembic commands ###
