"""Fix tag's association table

Revision ID: 797514f13070
Revises: 8af38383af50
Create Date: 2019-05-11 08:57:15.386441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797514f13070'
down_revision = '8af38383af50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_association', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_constraint('tags_association_project_id_fkey', 'tags_association', type_='foreignkey')
    op.create_foreign_key(None, 'tags_association', 'tasks', ['task_id'], ['id'])
    op.drop_column('tags_association', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_association', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags_association', type_='foreignkey')
    op.create_foreign_key('tags_association_project_id_fkey', 'tags_association', 'projects', ['project_id'], ['id'])
    op.drop_column('tags_association', 'task_id')
    # ### end Alembic commands ###
