"""fix tags table

Revision ID: d7edea05b2fe
Revises: 797514f13070
Create Date: 2019-05-11 09:01:35.440115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7edea05b2fe'
down_revision = '797514f13070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tags_project_id'), 'tags', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tags', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_project_id'), table_name='tags')
    op.drop_column('tags', 'project_id')
    # ### end Alembic commands ###
